# Generated by Django 2.2.8 on 2020-01-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=128)),
                ('ingredients', models.ManyToManyField(to='app_recipe.Ingredient')),
            ],
        ),
    ]
