# Generated by Django 2.2.8 on 2020-01-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipe', '0003_auto_20200127_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(null=True, to='app_recipe.Category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisines',
            field=models.ManyToManyField(null=True, to='app_recipe.Cuisine'),
        ),
    ]
