# Generated by Django 2.2.8 on 2020-01-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipe', '0005_auto_20200128_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
