# Generated by Django 2.2.8 on 2020-01-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipe', '0006_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='app_recipe.RecipeIngredientQuantityUnit', to='app_recipe.Ingredient'),
        ),
    ]
