# Generated by Django 2.2.8 on 2020-01-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipe', '0008_recipe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientquantityunit',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
