# Generated by Django 2.2.8 on 2020-01-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipe', '0011_auto_20200128_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'permissions': (('change_password', 'Can change password'),)},
        ),
    ]
